services:

  # MongoDB is Added
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  # Backend is Added
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend
    image: "mern-backend:jenkins"
    restart: unless-stopped
    env_file:
      - ./backend/.env
    expose:
      - "5000"
    depends_on:
      - mongo
    networks:
      - mern-network

  # Frontend is Added
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        VITE_API_URL: "/api"
    container_name: frontend
    image: "mern-frontend:jenkins"
    restart: unless-stopped
    expose:
      - "5173"
    depends_on:
      - backend
    networks:
      - mern-network

  # Nginx is Added
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - mern-network

volumes:
  mongo-data:

networks:
  mern-network:
    driver: bridge