services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://20.40.52.150:5000/api
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend