services:

  # MongoDB is Added
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network
# Backend is Added
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mern-network

# Frontend is Added
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        VITE_API_URL: http://localhost:5000/api
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mern-network


volumes:
  mongo-data:


networks:
  mern-network:
    driver: bridge