apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-part3
  labels:
    app: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: backend:local
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: app-config

          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/taskdb"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3


---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devops-part3

spec:
  selector:
    app: backend

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

  type: ClusterIP