name: build-and-lint

on:
  push:
    branches: ["Main", "dev"]
  pull_request:
    branches: ["Main", "dev"]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      # Backend

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Lint backend
        working-directory: backend
        run: npm run lint -- --max-warnings=0

      # Frontend

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint -- --max-warnings=0

      # Docker build
      - name: build backend image
        run: docker build -t backend ./backend

      - name: build frontend image
        run: docker build -t frontend ./frontend
