name: build-and-lint

on:
  push:
    branches: ["Main", "dev"]
  pull_request:
    branches: ["Main", "dev"]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      # Backend

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Lint backend
        working-directory: backend
        run: npm run lint -- --max-warnings=0

      # Frontend

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint -- --max-warnings=0

      # Docker build

      - name: Build backend image
        run: docker build -t backend ./backend

      - name: Build frontend image
        run: docker build -t frontend ./frontend

  deploy:
    needs: build-and-lint
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add Azure host to known_hosts
        run: |
          set -x
          mkdir -p ~/.ssh
          echo "AZURE_HOST value is: [$AZURE_HOST]"
          ssh-keyscan -T 10 -H "$AZURE_HOST" >> ~/.ssh/known_hosts
        env:
          AZURE_HOST: ${{ secrets.AZURE_HOST }}

      - name: Write SSH key
        run: |
          echo "${AZURE_KEY}" > mern-server_key.pem
          chmod 600 mern-server_key.pem
        env:
          AZURE_KEY: ${{ secrets.AZURE_KEY }}

      - name: Deploy on Azure
        env:
          AZURE_HOST: ${{ secrets.AZURE_HOST }}
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_APP_DIRECTORY: ${{ secrets.AZURE_APP_DIRECTORY }}

        run: |
          ssh -i mern-server_key.pem ${AZURE_USER}@${AZURE_HOST} << EOF

          set -e

          cd "${AZURE_APP_DIRECTORY}"

          git fetch --all

          git reset --hard origin/Main

          docker compose up -d --build

          docker image prune -f

          docker compose ps

          EOF
          